ext {
    //通过scripts/config.gradle获取到设置的源码路径，
    //这里也可以改成自己定义的路径
    aospDir = rootProject.ext.aospRoot

    aospOutRoot = rootProject.ext.aospOutRoot

    car = [
            rootDir   : "$aospDir",
            rootOutDir: "$aospOutRoot",

            /*************** 配置原生 car-framework 路径 ***************/
            Framework : [
                    manifest: "$aospDir/packages/services/Car/car-lib/AndroidManifest.xml",
                    res     : [
                            "$aospDir/packages/services/Car/FrameworkPackageStubs/res/",
                            "$aospDir/packages/services/Car/car-admin-ui-lib/src/main/res",
                    ],
                    assets  : [],
                    jni     : "",
                    src     : [
                            "$aospDir/packages/services/Car/FrameworkPackageStubs/src",//CarFrameworkPackageStubs
                            "$aospDir/packages/services/Car/car-admin-ui-lib/src/main/java",//car-admin-ui-lib
                            "$aospDir/packages/services/Car/car-builtin-lib/src",//android.car.builtin
                            "$aospDir/packages/services/Car/car-evs-helper-lib/src",//car-evs-helper-lib
                            "$aospDir/packages/services/Car/car-helper-lib/src",//car-helper-lib
                            "$aospDir/packages/services/Car/car-lib/src",//android.car-module
                            "$aospDir/frameworks/opt/car/services/updatableServices/src",//car-frameworks-service-module
                            "$aospDir/frameworks/opt/car/services/builtInServices/src_imms",//car-frameworks-service
                            "$aospDir/frameworks/opt/car/services/builtInServices/src",//car-frameworks-service
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car-builtin-lib/android.car.builtin.stubs.source.system/android_common/gen/logtags/packages/services/Car/car-builtin-lib/src",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car-builtin-lib/android.car.builtin.stubs.source.module_lib/android_common/gen/logtags/packages/services/Car/car-builtin-lib/src",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car-builtin-lib/android.car.builtin.stubs.source/android_common/gen/logtags/packages/services/Car/car-builtin-lib/src",
                    ],
                    srcjars : [
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/FrameworkPackageStubs/CarFrameworkPackageStubs/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car-admin-ui-lib/car-admin-ui-lib/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car-evs-helper-lib/car-evs-helper-lib/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car-helper-lib/car-helper-lib/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car-lib-module/android.car-module/android_common/gen/aidl",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car-lib-module/android.car-module/android_common_apex33/gen/aidl",

                    ],
                    aidl    : [],
            ],

            /*************** 配置原生 car-services 路径 ***************/
            Services  : [
                    manifest: "$aospDir/packages/services/Car/service/AndroidManifest.xml",
                    res     : [
                            "$aospDir/packages/services/Car/service/res",
                            "$aospDir/packages/services/Car/service-builtin/res",
                    ],
                    assets  : [],
                    jni     : "",
                    src     : [
                            "$aospDir/packages/services/Car/service-builtin/src",
                            "$aospDir/packages/services/Car/service/src",
                    ],
                    srcjars : [
                            "$aospOutRoot/out/soong/.intermediates/frameworks/opt/car/services/builtInServices/tests/FrameworkOptCarServicesTest/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/frameworks/opt/car/services/updatableServices/tests/FrameworkOptCarServicesUpdatableTest/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/car_product/car_ui_portrait/rro/CarUiPortraitCarServiceRRO/CarUiPortraitCarServiceRRO/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/experimental/service/ExperimentalCarService/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/experimental/tests/experimentalcarservice_unit_test/ExperimentalCarServiceTests/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service-builtin/CarService/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatable/android_common/gen/aidl",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatable/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatable/android_common/gen/proto",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatable/android_common_apex33/gen/aidl",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatable/android_common_apex33/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatable/android_common_apex33/gen/proto",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatableNonModule/android_common/gen/aidl",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatableNonModule/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/service/CarServiceUpdatableNonModule/android_common/gen/proto",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/tests/OemCarServiceTestApp/OemCarServiceTestApp/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/tests/carservice_test/CarServiceTest/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/tests/carservice_unit_test/CarServiceUnitTest/android_common/gen/aidl",
                            "$aospOutRoot/out/soong/.intermediates/packages/services/Car/tests/carservice_unit_test/CarServiceUnitTest/android_common/gen/android",
                    ],
                    aidl    : [],
            ],

            /*************** 配置原生 CarSystemUI 路径 ***************/
            SystemUI  : [
                    manifest: "$aospDir/packages/apps/Car/SystemUI/AndroidManifest.xml",
                    res     : [
                            "$aospDir/packages/apps/Car/SystemUI/res-keyguard",
                            "$aospDir/packages/apps/Car/SystemUI/res",
                            "$aospDir/packages/apps/Car/SystemUI/samples/sample2/rro/res",
                            "$aospDir/packages/apps/Car/SystemUI/samples/sample3/rro/res",
                            "$aospDir/packages/apps/Car/SystemUI/samples/sample1/rro/res",
                    ],
                    assets  : [],
                    jni     : "",
                    src     : [
                            "$aospDir/packages/apps/Car/SystemUI/src",

                    ],
                    srcjars : [
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SystemUI/CarSystemUI-core/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SystemUI/CarSystemUI-core/android_common/kapt",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SystemUI/CarSystemUI-tests/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SystemUI/CarSystemUI-tests/android_common/kapt",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SystemUI/CarSystemUI/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SystemUI/samples/sample1/rro/CarSystemUISampleOneRRO/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SystemUI/samples/sample2/rro/CarSystemUISampleTwoRRO/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SystemUI/samples/sample3/rro/CarSystemUISampleThreeRRO/android_common/gen/android",
                    ],
                    aidl    : [],
            ],

            /*************** 配置原生 CarSettings 路径 ***************/
            Settings  : [
                    manifest: "$aospDir/packages/apps/Car/Settings/AndroidManifest.xml",
                    res     : [
                            "$aospDir/packages/apps/Car/Settings/res",

                    ],
                    assets  : [],
                    jni     : "",
                    src     : [
                            "$aospDir/packages/apps/Car/Settings/src",
                    ],
                    srcjars : [
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/Settings/CarSettings-core/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/Settings/CarSettings/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/Settings/CarSettingsForTesting/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/Settings/CarSettingsForUnitTesting/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/Settings/tests/unit/CarSettingsUnitTests/android_common/gen/android",
                            "$aospOutRoot/out/soong/.intermediates/packages/apps/Car/SettingsIntelligence/CarSettingsIntelligence/android_common/gen/android",
                    ],
                    aidl    : [],
            ],
    ]

}
