apply from: "${rootDir}/scripts/func.gradle"

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-parcelize'

ext {
    USE_PLUGIN = "android"
}

android {
    namespace 'aosp.' + project.getName()
    def androidSdk = rootProject.ext.androidSdk
    compileSdkVersion androidSdk.compileSdkVersion
    buildToolsVersion androidSdk.buildToolsVersion
    defaultConfig {
        minSdkVersion androidSdk.minSdkVersion
        targetSdkVersion androidSdk.targetSdkVersion

        if (project.hasProperty('BUILD_NATIVE_ROOT') && isNotNull(BUILD_NATIVE_ROOT)) {
            logger.warn(project.getName() + " config c/cpp code, root dir = " + BUILD_NATIVE_ROOT)
            externalNativeBuild {
                cmake {
                    arguments "-DBUILD_NATIVE_ROOT=" + BUILD_NATIVE_ROOT
                    if (project.hasProperty('BUILD_NATIVE_OUT_ROOT') && isNotNull(BUILD_NATIVE_OUT_ROOT)) {
                        arguments "-DBUILD_NATIVE_OUT_ROOT=" + BUILD_NATIVE_OUT_ROOT
                    }
                }
            }
        }
    }

    sourceSets {
        main {
            if (project.hasProperty('BUILD_ASSETS') && isNotNull(BUILD_ASSETS)) {
                assets.srcDirs = [BUILD_ASSETS]
            }

            if (project.hasProperty('BUILD_RES') && isNotNull(BUILD_RES)) {
                res.srcDirs = [BUILD_RES]
            }

            if (project.hasProperty('BUILD_SRC') && isNotNull(BUILD_SRC)) {
                java.srcDirs = [BUILD_SRC, rootProject.ext.aosp_srcjars_dir]
            }

            if (rootProject.ext.build_aidl.toBoolean() &&
                    project.hasProperty('BUILD_AIDL') && isNotNull(BUILD_AIDL)) {
                aidl.srcDirs = [BUILD_AIDL]
            }
        }
    }

    if (project.hasProperty('BUILD_NATIVE_ROOT') && isNotNull(BUILD_NATIVE_ROOT)) {
        externalNativeBuild {
            cmake {
                path "CMakeLists.txt"
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        //这里不加 build_aidl 熟悉判断的原因是:
        //如果加了判断，改 false 后，as就不会把生成的java当做源文件对待
        aidl = true
    }
}

task deleteAndroidSdk {
    doLast {
        def platformVersion = android.compileSdkVersion
        def androidJarPath = "${android.sdkDirectory}/platforms/${platformVersion}/android.jar"
        def androidJarPathBackup = "${android.sdkDirectory}/platforms/${platformVersion}/android.jar.backup"

        // 获取 android.jar 的 File 对象
        def androidJarFile = file(androidJarPath)

        // 检查 android.jar 是否存在
        if (androidJarFile.exists()) {
            // 将 android.jar 重命名为 android.jar.backup
            androidJarFile.renameTo(androidJarPathBackup)
            println("Task deleteAndroidSdk: ${androidJarPath} renamed to ${androidJarPathBackup}")
        } else {
            println("Task deleteAndroidSdk: ${androidJarPath} not found")
        }
    }
}

task restoreAndroidSdk {
    doLast {
        def platformVersion = android.compileSdkVersion
        def androidJarPath = "${android.sdkDirectory}/platforms/${platformVersion}/android.jar"
        def androidJarPathBackup = "${android.sdkDirectory}/platforms/${platformVersion}/android.jar.backup"

        // 获取 android.jar.backup 的 File 对象
        def androidJarBackupFile = file(androidJarPathBackup)

        // 检查 android.jar.backup 是否存在
        if (androidJarBackupFile.exists()) {
            // 将 android.jar.backup 重命名为 android.jar
            androidJarBackupFile.renameTo(androidJarPath)
            logger.warn("task restoreAndroidSdk project = " + project.name + ", " + androidJarPathBackup + ", renamed to " + androidJarPath)
        } else {
            logger.warn("task restoreAndroidSdk project = " + project.name + ", " + androidJarPathBackup + " not found")
        }
    }
}

apply from: "${rootDir}/scripts/task.gradle"
