ext.getCurrentVersion = {
    def file = file("VERSION")
    def content = ''

    file.withInputStream { inputStream ->
        content = inputStream.text
    }

    return content
}

ext.getRemoteVersion = {
    // 定义网络文件的 URL
    def url = new java.net.URL('https://raw.githubusercontent.com/i-rtfsc/as-aosp/oppo/VERSION')
    // 读取网络文件内容
    def content = ''
    url.openStream().withReader { reader ->
        content = reader.text
    }
}

ext.convertVersionToInt = { version ->
    def parts = version.tokenize('.').collect { it as Integer }

    def intValue = 0
    for (int i = 0; i < parts.size(); i++) {
        intValue = intValue * 10 + parts[i]
    }

    return intValue
}

ext.applyConfig = { file ->
    def asbPath = "${rootDir}/" + file
    logger.warn(asbPath)
    File f = new File(asbPath)
    if (f.exists() && f.isFile()) {
        apply from: asbPath
    }
}

ext.isNotNull = { value ->
    if (!(value == null || value.isEmpty())) {
        return true
    } else {
        return false
    }
}

ext.getModules = { subprojects ->
    def allModules = [:]
    for (Project subproject : subprojects) {
        def project_name = subproject.getName().toString()
        logger.debug(project_name)
        allModules.put(project_name, ":" + project_name)
    }

    return allModules
}

ext.getExtProperties = {
    Properties properties = new Properties()
    try {
        // 检查 ext/scripts/ext.properties 是否存在
        properties.load(project.rootProject.file('ext/scripts/ext.properties').newDataInputStream())
    } catch (Exception e) {
        logger.warn("has not ext/scripts/ext.properties, " + e)
        properties.load(project.rootProject.file('local.properties').newDataInputStream())
    }

    return properties
}

ext.getRoot = { properties ->
    // 检查 ext/scripts/ext.properties or local.properties 是否存在 EXT_AOSP_ROOT
    // 方便其他用户自定义此工程的同时也能随时同步最新代码
    def aospRoot = properties.getProperty('EXT_AOSP_ROOT')
    if (isNotNull(aospRoot)) {
        logger.warn("set aosp root from ext/scripts/ext.properties or local.properties")
    } else {
        logger.warn("has not set ext aosp root")
        //设置源码所在的目录
        aospRoot = "/home/solo/code/oppo"
        if (org.gradle.internal.os.OperatingSystem.current().isMacOsX()) {
            aospRoot = "/Users/solo/code/oppo"
        }
    }
    // win系统 需要转换，不然 cmake 无法识别路径
    if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
        aospRoot = aospRoot.replace('\\', '/')
    }
    logger.warn("aospRoot = " + aospRoot)

    return aospRoot
}

ext.getOutRoot = { properties, root_dir ->
    // 检查 ext/scripts/ext.properties or local.properties 是否存在 EXT_AOSP_OUT_ROOT
    // 方便其他用户自定义此工程的同时也能随时同步最新代码
    def aospOutRoot = properties.getProperty('EXT_AOSP_OUT_ROOT')
    if (isNotNull(aospOutRoot)) {
        logger.warn("set aosp out root from ext/scripts/ext.properties or local.properties")
    } else {
        logger.warn("has not set ext aosp out root")
        // 未设置额外的 out 目录，则默认是在源码根目录下
        aospOutRoot = root_dir
    }
    // win系统 需要转换，不然 cmake 无法识别路径
    if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
        aospOutRoot = aospOutRoot.replace('\\', '/')
    }
    logger.warn("aospOutRoot = " + aospOutRoot)

    return aospOutRoot
}

ext.getIdea = { ->
    def isIdea = (System.getenv("IDEA_INITIAL_DIRECTORY") != null)
    if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
        def command = System.properties['sun.java.command']
        if (command != null) {
            if (command.contains('idea') || command.contains('Idea')) {
                isIdea = true
            } else {
                isIdea = false
            }
        }
    }

    return isIdea
}

ext.getAndroidStudio = { ->
    def isRunningInIDEA = System.getenv("IDEA_INITIAL_DIRECTORY") != null
    def isRunningInAndroidStudio = !isRunningInIDEA && System.getProperty('idea.active') != null

    if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
        def command = System.properties['sun.java.command']
        if (command != null) {
            if (command.contains('AndroidStudio') || command.contains('gradle')) {
                isRunningInAndroidStudio = true
            }
        }
    }

    return isRunningInAndroidStudio
}

ext.getForceAndroidLibrary = { properties ->
    // 检查 ext/scripts/ext.properties or local.properties 是否存在 EXT_FORCE_ANDROID_LIBRARY
    def forceAndroidLibrary = properties.getProperty('EXT_FORCE_ANDROID_LIBRARY')
    if (isNotNull(forceAndroidLibrary)) {
        logger.warn("set forceAndroidLibrary from ext/scripts/ext.properties or local.properties")
        forceAndroidLibrary = forceAndroidLibrary.toBoolean()
    } else {
        // 经过测试发现，在 as 或者 idea 中使用 Java 模块也都可以断点调试
        // 使用改成默认用 Java 模块
        if (false) {
            // 判断是否在中 as 中运行，
            def isRunningInIDEA = System.getenv("IDEA_INITIAL_DIRECTORY") != null
            def isRunningInAndroidStudio = !isRunningInIDEA && System.getProperty('idea.active') != null
            logger.warn("Running on as = " + isRunningInAndroidStudio)
            forceAndroidLibrary = isRunningInAndroidStudio
        } else {
            forceAndroidLibrary = false
        }
    }

    return forceAndroidLibrary
}
