tasks.register('copyAospScrjar') {
    if (project.hasProperty('BUILD_SRC_JARS') && isNotNull(BUILD_SRC_JARS)) {
        def src_jars = "\"" + BUILD_SRC_JARS.join('#') + "\""// 将列表转换为以#号隔开的字符串
        def project_src_jars_dir = project.projectDir.toString() + File.separator + rootProject.ext.aosp_srcjars_dir
        def scriptFile = "${rootDir}" + File.separator + "scripts" + File.separator + "copy_aosp_scrjar.py"
        def cmd = "python " + scriptFile + " -m " + project_src_jars_dir + " -s " + src_jars
        logger.warn("task copyAospScrjar, cmd = " + cmd)
        def process = cmd.execute()
        process.waitFor()
    } else {
        logger.warn("task copyAospScrjar, src_jars was null")
    }
}

dependencies {
    if (project.hasProperty('BUILD_NATIVE_ROOT') && isNotNull(BUILD_NATIVE_ROOT)) {
        logger.warn("Native [" + project.getName() + "] don't dependence other project")
    } else {
        rootProject.ext.allModules.each { dependence ->
            if (dependence.key == project.name) {
                logger.warn("Don't compileOnly myself, project = " + project.name)
                if (project.hasProperty('USE_PLUGIN') && isNotNull(USE_PLUGIN)) {
                    logger.warn("Running plugin = " + USE_PLUGIN)
                }
            } else {
                if (rootProject.ext.build_aidl.toBoolean()) {
                    logger.warn("don't compileOnly forEach when build aidl")
                } else {
                    def project = project(dependence.value)
                    def projectDir = project.projectDir
                    def cmakeListsFile = new File(projectDir, "CMakeLists.txt")
                    if (cmakeListsFile.exists()) {
                        logger.warn("Don't compileOnly native project = " + project.name)
                    } else {
                        compileOnly project
                    }
                }
            }
        }
    }
    // execute task
    copyAospScrjar
}
