def androidRoot = rootProject.ext.aosp

ext {
    BUILD_MANIFEST = ""
    BUILD_RES = ""
    BUILD_ASSETS = ""
    BUILD_SRC = ""
    BUILD_SRC_JARS = ""
    BUILD_AIDL = ""
    BUILD_NATIVE_ROOT = androidRoot.rootDir
    BUILD_NATIVE_OUT_ROOT = androidRoot.rootOutDir
}

// 这个模块是一个c/c++模块，
// 目前不知道怎么在 java-library 中引用 CmakeLists.txt
// 所以判断是 idea 则加载 java-library
// 否则加载 android-library
if (rootProject.ext.isIdea) {
    apply from: "${rootDir}/scripts/java-build.gradle"
} else {
    apply from: "${rootDir}/scripts/android-build.gradle"
}
