def androidRoot = rootProject.ext.aosp

ext {
    BUILD_MANIFEST = ""
    BUILD_RES = ""
    BUILD_ASSETS = ""
    BUILD_SRC = ""
    BUILD_SRC_JARS = ""
    BUILD_AIDL = ""
    BUILD_NATIVE_ROOT = androidRoot.rootDir
    BUILD_NATIVE_OUT_ROOT = androidRoot.rootOutDir
}

apply from: "${rootDir}/scripts/android-build.gradle"
